# -------------------------
#  Project Configuration
#  Generated by AI
# -------------------------

TARGET := server

SRC_DIR := src
BUILD_DIR := build

# All source files
SRCS := main.c route_handler.c $(wildcard $(SRC_DIR)/*.c)

# Object files in build/
OBJS := $(SRCS:%.c=$(BUILD_DIR)/%.o)

# Compiler settings
CC := gcc
CFLAGS := -Wall -Wextra -Werror -std=c11 -I$(SRC_DIR) -O2
LDFLAGS := 

# For debugging: make debug
DEBUG_FLAGS := -g -O0

# -------------------------
#  Default Rule
# -------------------------
all: $(TARGET)

# -------------------------
#  Link the final output
# -------------------------
$(TARGET): $(OBJS)
	$(CC) $(OBJS) -o $@ $(LDFLAGS)
	@echo "✔ Build complete → ./$(TARGET)"

# -------------------------
#  Build object files
# -------------------------
$(BUILD_DIR)/%.o: %.c | $(BUILD_DIR)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -MMD -MP -c $< -o $@

# Create build/ directory
$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

# -------------------------
#  Debug build
# -------------------------
debug: CFLAGS += $(DEBUG_FLAGS)
debug: clean all

# -------------------------
#  Clean build files
# -------------------------
clean:
	rm -rf $(BUILD_DIR) $(TARGET)

# Include dependency files
-include $(OBJS:.o=.d)

.PHONY: all clean debug
